import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

import { cn } from "@/lib/utils";
import { auth } from "@/auth/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next Auth Toolbox",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <html lang="en">
                <head>
                    <link
                        rel="icon"
                        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🔐</text></svg>"
                    ></link>
                </head>
                <body
                    className={cn(
                        inter.className,
                        "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-400 to-blue-800"
                    )}
                >
                    <Toaster></Toaster>
                    {children}
                </body>
            </html>
        </SessionProvider>
    );
}
